name: CI

on:
  push:
    branches:
      - master
      - develop

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code 
        uses: actions/checkout@v2
      
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      
      - name: Run unittests
        run: |
          pytest test/test.py 
      
      